ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
baseurl = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "DevGin"
theme = "hugo-theme-dream"

googleAnalytics = "G-QC9LEQ5FG6"
disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = ""
  # description = ""
  avatar = "/img/avatar.png"
  motto = "DevGin"

  # rss = true

  # utterancesRepo = ""
  
  email = "mark.gingrass@gmail.com"
  twitter = "MarkGingrass"
  # facebook = ""
  # instagram = ""
  linkedin = "markgingrass/"
  github = "mtgingrass"
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2021

  # favicon = "/favicon.ico"

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
  
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    
[params.adsense]
client = "ca-pub-2476238133050345"
inArticleSlot = "7562449572"

custom_css = ["css/custom.css"]
custom_js = ["js/custom.js"]